#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
#fvwm2 &
blackbox &
sleep 3
vncconfig -iconic &
x-terminal-emulator -ls -title "$VNCDESKTOP Desktop" -e top&

